- package.json
- src/intl/i18n.ts
- yarn.lock
> Default message for non translated messages

- src/app/[locale]/globals.css
> Add scrollbar styling

- README.md
- src/intl/dictionaries/en-US.json
> fix(docs): some typos.

- src/app/[locale]/dashboard/@board/BoardContainer.tsx
- src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
- src/app/[locale]/dashboard/@promptForm/actions.tsx
- src/stores/board-store.ts
> Feature/Render the board after submit PromptForm

- src/app/[locale]/dashboard/@board/layout.tsx
- src/app/[locale]/dashboard/@board/page.tsx
- src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
- src/stores/board-slice.ts
> Feature/show initial board UI

- src/app/[locale]/dashboard/@board/BoardContainer.tsx
- src/app/[locale]/dashboard/@board/InitialContent.tsx
- src/app/[locale]/dashboard/styles.module.css
- src/app/[locale]/globals.css
- src/lib/cboard-ai-engine/cboard-adapter.ts
On this PR:
- Change InitialContent and BoardContainer background color
- Change Export to Cboard button color to primary
- Change tiles background color to DEFAULT value
close #79
> Improve / Change colors

- src/app/[locale]/dashboard/@board/InitialContent.tsx
- src/app/[locale]/dashboard/@promptForm/GridSizeSelect.tsx
- src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
- src/stores/prompt-slice.ts
> Feature/Preprare the Entire PromptForm to be a controlled component

- src/components/Symbol/Symbol.tsx
> Use key prop for CircleIcon elements

- src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
- src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
> Feature / Use user languange on board creation

- src/app/[locale]/signin/Login/Dialog.tsx
- src/app/[locale]/signin/OAuth/Button.tsx
- src/app/[locale]/signin/Signin.tsx
- src/components/Alert/Alert.tsx
> Fix/Login Issues

- src/app/[locale]/dashboard/[id]/NewBoardLink/NewBoardLink.tsx
- src/app/[locale]/dashboard/[id]/NewBoardLink/styles.ts
- src/app/[locale]/dashboard/[id]/Topbar/Topbar.tsx
- src/app/[locale]/dashboard/[id]/Topbar/styles.ts
On this PR:
- Use grid to divide the top bar on three equals container
- Center top bar title
- Show button or icon button depending on screen sizes
> Improve / Top bar

- src/app/[locale]/dashboard/[id]/layout.tsx
On this PR:
- Fix app and drawer paddings
- Fix drawer background color
- Remove unnecesary style
> Improve / root layout

- src/app/[locale]/dashboard/[id]/@board/Grid/Row/Row.tsx
- src/app/[locale]/globals.css
On this PR:
- The tile row height was adjusted to prevent cuts in the printed PDF.
> Fix / Print boards

- src/app/[locale]/(dashboard)/layout.tsx
- src/app/[locale]/(dashboard)/styles.ts
> separate the sx styles from the (dashboard) layout file

- src/app/[locale]/(dashboard)/board/[id]/page.tsx
- src/app/[locale]/(dashboard)/components/savedData/SavedData.tsx
- src/components/IntlAsyncComponentProvider/IntlAsyncComponentProvider.tsx
this is for changing function name issue
close #129
> change function name

- src/app/[locale]/(dashboard)/board/[id]/components/actions.ts
- src/app/[locale]/(dashboard)/board/[id]/page.tsx
- src/app/[locale]/(dashboard)/board/components/promptForm/actions.tsx
- src/app/[locale]/(dashboard)/components/savedData/history/History.tsx
- src/app/[locale]/(dashboard)/components/savedData/history/actions.ts
- src/app/[locale]/(dashboard)/components/savedData/savedBoards/SavedBoard.tsx
- src/app/[locale]/(dashboard)/components/savedData/savedBoards/actions.ts
> Feature / revalidate cache

- src/components/TileEditorModal/css/embla.css
Improved the title color during board editing to enhance readability by increasing contrast, addressing previous issues with low visibility.
close #226
> Changed the color of title

- src/app/[locale]/(dashboard)/board/[id]/components/BoardContainer.tsx
- src/app/[locale]/(dashboard)/board/[id]/components/Toolbar.tsx
Added icon in Toolbar to control drag and drop of the boards.
close #225
> Added icon for drag and drop

- public/images/index.ts
- src/app/[locale]/signin/Signin.tsx
Reverts cboard-org/cboard-ai-builder#230
> Revert "Removed "unoptimized" prop from Image tag and fixed lint-staged issue"

- src/app/[locale]/(dashboard)/components/savedData/savedBoards/SavedBoardList.tsx
- src/app/[locale]/signin/actions.ts
- src/app/[locale]/signin/page.tsx
> Fix / Purge cached tags on login page
